import Rowl.Prototype
import Rowl.Probes
import Rowl.OwlSemantics
import Rowl.OwlLaws
import Rowl.OwlExamples
import Rowl.Imports
import Rowl.Prepare
import Rowl.Typing
import Rowl.Unicode
import Rowl.Snapshot
import Rowl.Batch
import Rowl.Collection
import Rowl.Symbols
import Rowl.Builtins
import Rowl.Indexing
import Rowl.Rdf
import Rowl.Vocabulary
import Rowl.Regular
import Rowl.Iri
import Rowl.Anonymous
import Rowl.Encoding
import Rowl.LangTag
import Rowl.NTriples
import Rowl.TopData
import Rowl.Roles
import Rowl.RoleClosure
import Rowl.RoleOrder
import Rowl.AnonymousGraph
import Rowl.AssertionEquality
import Rowl.AnonymousMultiplicity
import Rowl.AnonymousBoundary
import Rowl.AnonymousRestrictions
import Rowl.RangeEquality
import Rowl.DatatypeDefinitions
import Rowl.DatatypeOrder
import Rowl.DatatypePositions
import Rowl.DatatypeRestrictions
import Rowl.ClassEquality
import Rowl.Keys
import Rowl.Arity
import Rowl.AxiomEquality
import Rowl.StructuralCongruence
import Rowl.AxiomSet
import Rowl.Names
import Rowl.Prefixes
import Rowl.Longest
import Rowl.Functional
import Rowl.FunctionalSelection
import Rowl.FunctionalPayload
import Rowl.FunctionalLexer
import Rowl.FunctionalDisjointness
import Rowl.Decimal
import Rowl.FunctionalIntegers
import Rowl.SourceSpans
import Rowl.FunctionalNames
import Rowl.FunctionalIriParts
import Rowl.FunctionalIris
import Rowl.FunctionalPrefixShape
import Rowl.FunctionalPrefixDeclaration
import Rowl.FunctionalPrefixes
import Rowl.FunctionalPrefixResolution
import Rowl.FunctionalHeaderIdentity
import Rowl.FunctionalHeaderShape
import Rowl.FunctionalHeaderImport
import Rowl.FunctionalHeader
import Rowl.FunctionalHeaderSource
import Rowl.FunctionalLiteralShape
import Rowl.FunctionalLiteralValues
import Rowl.FunctionalLiterals
import Rowl.FunctionalLiteralSource
import Rowl.FunctionalAnnotationParts
import Rowl.FunctionalAnnotations
import Rowl.FunctionalAnnotationSource

#print axioms Rowl.next_valuation_total_correct
#print axioms Rowl.evaluate_total_correct
#print axioms Rowl.decide_loop_step
#print axioms Rowl.decide_total_correct
#print axioms Rowl.decide_sound
#print axioms Rowl.decide_complete
#print axioms Rowl.decide_terminates
#print axioms Rowl.Probes.add_total_correct
#print axioms Rowl.Probes.lookup_total_correct
#print axioms Rowl.Probes.replace_slot_total_correct
#print axioms Rowl.Probes.decimal_digit_total_correct
#print axioms Rowl.Owl.nonempty_arity
#print axioms Rowl.Owl.at_least_two_arity
#print axioms Rowl.Owl.literal_lexical_utf8
#print axioms Rowl.Owl.domains_disjoint
#print axioms Rowl.Owl.invert_total_correct
#print axioms Rowl.Owl.invert_semantics
#print axioms Rowl.Owl.at_least_zero
#print axioms Rowl.Owl.at_most_one_iff
#print axioms Rowl.Owl.exactly_one_singleton
#print axioms Rowl.Owl.infinite_cardinality
#print axioms Rowl.Owl.data_complement_entire_domain
#print axioms Rowl.Owl.literal_values_coalesce
#print axioms Rowl.Owl.datatype_embedding_preserves_distinct_values
#print axioms Rowl.Owl.universal_vacuity
#print axioms Rowl.Owl.existential_without_named_requirement
#print axioms Rowl.Owl.functional_forces_equality
#print axioms Rowl.Owl.functional_difference_conflict
#print axioms Rowl.Owl.functionality_counts_denotations
#print axioms Rowl.Owl.maintenance_follows
#print axioms Rowl.Owl.chain_append
#print axioms Rowl.Owl.key_ignores_unnamed_subjects
#print axioms Rowl.Owl.key_requires_named_object_fillers
#print axioms Rowl.Owl.annotations_irrelevant
#print axioms Rowl.Owl.declarations_irrelevant
#print axioms Rowl.Owl.satisfaction_gives_model
#print axioms Rowl.Owl.anonymous_reassignment_invariant
#print axioms Rowl.Owl.anonymous_reassignment_preserves_interpretation
#print axioms Rowl.Owl.inconsistent_entails_everything
#print axioms Rowl.Owl.Examples.unused_native_values_do_not_expand_domain
#print axioms Rowl.Owl.Examples.valid_vocabulary
#print axioms Rowl.Owl.Examples.valid_singleton
#print axioms Rowl.Owl.Examples.empty_class_ontology_consistent
#print axioms Rowl.Owl.Examples.asserted_nothing_impossible
#print axioms Rowl.Owl.Examples.distinct_names_can_coincide
#print axioms Rowl.Owl.Examples.valid_boolean
#print axioms Rowl.Owl.Examples.anonymous_model_need_not_satisfy
#print axioms Rowl.Owl.Examples.unnamed_existential_witness
#print axioms Rowl.Imports.resolve_total_correct
#print axioms Rowl.Imports.resolve_complete_iff
#print axioms Rowl.Imports.resolve_terminates
#print axioms Rowl.Prepare.canonicalize_assertion_total_correct
#print axioms Rowl.Prepare.lower_subclass_total_correct
#print axioms Rowl.Prepare.prepare_axiom_total_correct
#print axioms Rowl.Prepare.preparation_preserves_anonymous_models
#print axioms Rowl.Typing.entity_kind_total_correct
#print axioms Rowl.Typing.validate_typing_total_correct
#print axioms Rowl.Typing.validate_typing_valid_iff
#print axioms Rowl.Unicode.byte_grammar_scalar_ranges
#print axioms Rowl.Unicode.xml_character_total_correct
#print axioms Rowl.Unicode.decode_next_total_correct
#print axioms Rowl.Unicode.read_text_total_correct
#print axioms Rowl.Unicode.rejected_excludes_text
#print axioms Rowl.Unicode.read_text_valid_iff
#print axioms Rowl.Unicode.read_text_terminates
#print axioms Rowl.Snapshot.check_sources_total_correct
#print axioms Rowl.Snapshot.check_sources_valid_iff
#print axioms Rowl.Snapshot.resolve_texts_total_correct
#print axioms Rowl.Snapshot.resolve_texts_complete_iff
#print axioms Rowl.Batch.prepare_all_total_correct
#print axioms Rowl.Batch.prepare_all_preserves_layout
#print axioms Rowl.Batch.prepare_all_preserves_models
#print axioms Rowl.Collection.class_entities_total_correct
#print axioms Rowl.Collection.range_entities_total_correct
#print axioms Rowl.Collection.entity_entities_total_correct
#print axioms Rowl.Collection.annotation_entities_total_correct
#print axioms Rowl.Collection.axiom_entities_total_correct
#print axioms Rowl.Collection.ontology_entities_total_correct
#print axioms Rowl.Collection.axiom_closure_entities_total_correct
#print axioms Rowl.Symbols.same_spelling_total_correct
#print axioms Rowl.Symbols.empty_total_correct
#print axioms Rowl.Symbols.lookup_total_correct
#print axioms Rowl.Symbols.key_of_total_correct
#print axioms Rowl.Symbols.intern_total_correct
#print axioms Rowl.Symbols.intern_preserves_existing_symbols
#print axioms Rowl.Symbols.symbols_distinguish_keys
#print axioms Rowl.Builtins.builtin_kind_total_correct
#print axioms Rowl.Indexing.index_entities_total_correct
#print axioms Rowl.Indexing.index_ontology_total_correct
#print axioms Rowl.Indexing.add_builtin_declarations_total_correct
#print axioms Rowl.Indexing.check_ontology_typing_total_correct
#print axioms Rowl.Indexing.indexed_identity_iff_spelling
#print axioms Rowl.Indexing.typing_iff_original_spelling
#print axioms Rowl.Indexing.check_ontology_typing_valid_iff_raw
#print axioms Rowl.Rdf.same_graph_name_total_correct
#print axioms Rowl.Rdf.select_graph_total_correct
#print axioms Rowl.Rdf.successful_selection_preserves_dataset
#print axioms Rowl.Rdf.missing_graph_iff
#print axioms Rowl.Rdf.default_selection_iff
#print axioms Rowl.Vocabulary.reserved_iri_total_correct
#print axioms Rowl.Vocabulary.entity_iri_allowed_total_correct
#print axioms Rowl.Vocabulary.check_reserved_vocabulary_total_correct
#print axioms Rowl.Vocabulary.check_reserved_vocabulary_valid_iff
#print axioms Rowl.Regular.copy_expression_total
#print axioms Rowl.Regular.nullable_total_correct
#print axioms Rowl.Regular.alternate_total_correct
#print axioms Rowl.Regular.sequence_total_correct
#print axioms Rowl.Regular.repeat_total_correct
#print axioms Rowl.Regular.derivative_total_correct
#print axioms Rowl.Regular.failure_excludes_utf8
#print axioms Rowl.Regular.matches_utf8_total_correct
#print axioms Rowl.Regular.matches_utf8_accepted_iff
#print axioms Rowl.Regular.matches_utf8_malformed_iff
#print axioms Rowl.Iri.at_most_iff
#print axioms Rowl.Iri.iri_grammar_total_correct
#print axioms Rowl.Iri.reference_grammar_total_correct
#print axioms Rowl.Iri.validate_iri_total_correct
#print axioms Rowl.Iri.validate_reference_total_correct
#print axioms Rowl.Iri.validate_iri_accepted_iff
#print axioms Rowl.Iri.validate_reference_accepted_iff
#print axioms Rowl.Anonymous.class_positions_total_correct
#print axioms Rowl.Anonymous.axiom_positions_total_correct
#print axioms Rowl.Anonymous.annotation_has_no_anonymous_total_correct
#print axioms Rowl.Anonymous.annotated_axiom_positions_total_correct
#print axioms Rowl.Anonymous.check_positions_total_correct
#print axioms Rowl.Anonymous.check_positions_valid_iff
#print axioms Rowl.Encoding.scalar_total_correct
#print axioms Rowl.Encoding.encode_total_correct
#print axioms Rowl.Encoding.encoded_unique
#print axioms Rowl.Encoding.encode_some_iff
#print axioms Rowl.Encoding.encode_none_iff
#print axioms Rowl.Encoding.encode_prefix_inverse
#print axioms Rowl.Encoding.decode_encoded_unit
#print axioms Rowl.LangTag.grammar_total_correct
#print axioms Rowl.LangTag.normal_grammar_total_correct
#print axioms Rowl.LangTag.well_formed_total_correct
#print axioms Rowl.LangTag.well_formed_accepted_iff
#print axioms Rowl.NTriples.at_total_correct
#print axioms Rowl.NTriples.required_total_correct
#print axioms Rowl.NTriples.expect_total_correct
#print axioms Rowl.NTriples.skip_comment_total_correct
#print axioms Rowl.NTriples.skip_comment_accepted_iff
#print axioms Rowl.NTriples.skip_total_correct
#print axioms Rowl.NTriples.skip_accepted_iff
#print axioms Rowl.NTriples.append_encoded_total_correct
#print axioms Rowl.NTriples.hex_total_correct
#print axioms Rowl.NTriples.token_classes_total_correct
#print axioms Rowl.NTriples.blank_end_total_correct
#print axioms Rowl.NTriples.blank_end_accepted_iff
#print axioms Rowl.NTriples.blank_tail_bounds
#print axioms Rowl.NTriples.copy_term_total_correct
#print axioms Rowl.NTriples.blank_total_correct
#print axioms Rowl.NTriples.blank_accepted_iff
#print axioms Rowl.NTriples.unicode_escape_total_correct
#print axioms Rowl.NTriples.unicode_escape_accepted_iff
#print axioms Rowl.NTriples.hex_digits_progress
#print axioms Rowl.NTriples.escape_total_correct
#print axioms Rowl.NTriples.escape_accepted_iff
#print axioms Rowl.NTriples.escape_value_progress
#print axioms Rowl.NTriples.quoted_item_total_correct
#print axioms Rowl.NTriples.quoted_item_progress
#print axioms Rowl.NTriples.quoted_item_accepted_iff
#print axioms Rowl.NTriples.quoted_total_correct
#print axioms Rowl.NTriples.quoted_accepted_iff
#print axioms Rowl.NTriples.quoted_token_progress
#print axioms Rowl.NTriples.read_iri_total_correct
#print axioms Rowl.NTriples.read_iri_accepted_iff
#print axioms Rowl.NTriples.subject_total_correct
#print axioms Rowl.NTriples.subject_accepted_iff
#print axioms Rowl.NTriples.tag_word_total_correct
#print axioms Rowl.NTriples.tag_word_accepted_iff
#print axioms Rowl.NTriples.tag_tail_total_correct
#print axioms Rowl.NTriples.tag_tail_accepted_iff
#print axioms Rowl.NTriples.tag_total_correct
#print axioms Rowl.NTriples.tag_accepted_iff
#print axioms Rowl.NTriples.tag_token_progress
#print axioms Rowl.NTriples.literal_kind_total_correct
#print axioms Rowl.NTriples.literal_kind_accepted_iff
#print axioms Rowl.NTriples.literal_total_correct
#print axioms Rowl.NTriples.literal_accepted_iff
#print axioms Rowl.NTriples.literal_token_progress
#print axioms Rowl.NTriples.object_total_correct
#print axioms Rowl.NTriples.object_accepted_iff
#print axioms Rowl.NTriples.subject_token_progress
#print axioms Rowl.NTriples.object_token_progress
#print axioms Rowl.NTriples.line_end_total_correct
#print axioms Rowl.NTriples.line_end_accepted_iff
#print axioms Rowl.NTriples.read_triple_total_correct
#print axioms Rowl.NTriples.read_triple_accepted_iff
#print axioms Rowl.NTriples.read_triple_token_progress
#print axioms Rowl.NTriples.read_with_limits_total_correct
#print axioms Rowl.NTriples.read_total_correct
#print axioms Rowl.NTriples.read_with_limits_accepted_iff
#print axioms Rowl.NTriples.read_accepted_iff
#print axioms Rowl.NTriples.document_count_bounded
#print axioms Rowl.TopData.axiom_allowed_total_correct
#print axioms Rowl.TopData.check_axioms_total_correct
#print axioms Rowl.TopData.check_axioms_valid_iff
#print axioms Rowl.Roles.class_requirements_total_correct
#print axioms Rowl.Roles.axiom_facts_total_correct
#print axioms Rowl.Roles.collect_facts_total_correct
#print axioms Rowl.Roles.expression_role_total_correct
#print axioms Rowl.Roles.inverse_role_total_correct
#print axioms Rowl.Roles.inverse_role_involutive
#print axioms Rowl.Roles.collect_facts_nodes_iff
#print axioms Rowl.Roles.collect_facts_hierarchy_iff
#print axioms Rowl.Roles.collect_facts_composite_iff
#print axioms Rowl.Roles.property_roles_total_correct
#print axioms Rowl.Roles.is_top_role_total_correct
#print axioms Rowl.RoleClosure.same_role_total_correct
#print axioms Rowl.RoleClosure.non_simple_closure_total_correct
#print axioms Rowl.RoleClosure.non_simple_closure_complete_iff
#print axioms Rowl.RoleClosure.hierarchy_target_nodes
#print axioms Rowl.RoleClosure.classify_non_simple_total_correct
#print axioms Rowl.RoleClosure.check_simplicity_total_correct
#print axioms Rowl.RoleClosure.check_simplicity_allowed_iff
#print axioms Rowl.RoleOrder.close_order_total_correct
#print axioms Rowl.RoleOrder.close_order_complete_iff
#print axioms Rowl.RoleOrder.chain_seeds_iff
#print axioms Rowl.RoleOrder.least_chain_order_total_correct
#print axioms Rowl.RoleOrder.forced_conflict_implies_irregular
#print axioms Rowl.RoleOrder.check_regularity_total_correct
#print axioms Rowl.RoleOrder.check_regularity_accepted_iff
#print axioms Rowl.AnonymousGraph.same_individual_total_correct
#print axioms Rowl.AnonymousGraph.key_injective
#print axioms Rowl.AnonymousGraph.connected_total_correct
#print axioms Rowl.AnonymousGraph.check_edges_total_correct
#print axioms Rowl.AnonymousGraph.check_edges_accepted_iff
#print axioms Rowl.AnonymousGraph.collect_edges_total_correct
#print axioms Rowl.AnonymousGraph.check_forest_total_correct
#print axioms Rowl.AnonymousGraph.check_forest_accepted_iff
#print axioms Rowl.AnonymousGraph.forest_components_are_trees
#print axioms Rowl.AssertionEquality.same_literal_total_correct
#print axioms Rowl.AssertionEquality.same_annotation_value_total_correct
#print axioms Rowl.AssertionEquality.same_individual_value_total_correct
#print axioms Rowl.AssertionEquality.same_property_total_correct
#print axioms Rowl.AssertionEquality.annotation_eq_refl
#print axioms Rowl.AssertionEquality.annotation_eq_symm
#print axioms Rowl.AssertionEquality.annotation_eq_trans
#print axioms Rowl.AssertionEquality.annotation_set_equivalence
#print axioms Rowl.AssertionEquality.same_annotation_total_correct
#print axioms Rowl.AssertionEquality.same_annotation_set_total_correct
#print axioms Rowl.AssertionEquality.same_object_assertion_total_correct
#print axioms Rowl.AnonymousMultiplicity.same_pair_total_correct
#print axioms Rowl.AnonymousMultiplicity.check_multiplicity_total_correct
#print axioms Rowl.AnonymousMultiplicity.check_multiplicity_accepted_iff
#print axioms Rowl.AnonymousBoundary.first_candidate_total_correct
#print axioms Rowl.AnonymousBoundary.second_candidate_total_correct
#print axioms Rowl.AnonymousBoundary.touches_named_total_correct
#print axioms Rowl.AnonymousBoundary.at_most_one_total_correct
#print axioms Rowl.AnonymousBoundary.check_boundary_total_correct
#print axioms Rowl.AnonymousBoundary.check_boundary_accepted_iff
#print axioms Rowl.AnonymousRestrictions.check_anonymous_total_correct
#print axioms Rowl.AnonymousRestrictions.check_anonymous_accepted_iff
#print axioms Rowl.RangeEquality.same_facet_total_correct
#print axioms Rowl.RangeEquality.same_literal_set_total_correct
#print axioms Rowl.RangeEquality.same_facet_set_total_correct
#print axioms Rowl.RangeEquality.range_eq_refl
#print axioms Rowl.RangeEquality.range_eq_symm
#print axioms Rowl.RangeEquality.range_eq_trans
#print axioms Rowl.RangeEquality.same_range_total_correct
#print axioms Rowl.RangeEquality.same_range_set_total_correct
#print axioms Rowl.RangeEquality.same_definition_total_correct
#print axioms Rowl.RangeEquality.definition_eq_refl
#print axioms Rowl.RangeEquality.definition_eq_symm
#print axioms Rowl.RangeEquality.definition_eq_trans
#print axioms Rowl.DatatypeDefinitions.predefined_total_correct
#print axioms Rowl.DatatypeDefinitions.defines_total_correct
#print axioms Rowl.DatatypeDefinitions.check_definitions_total_correct
#print axioms Rowl.DatatypeDefinitions.check_definitions_accepted_iff
#print axioms Rowl.DatatypeOrder.acyclic_iff_order
#print axioms Rowl.DatatypeOrder.order_on_iff_order
#print axioms Rowl.DatatypeOrder.reachable_total_correct
#print axioms Rowl.DatatypeOrder.check_dependencies_total_correct
#print axioms Rowl.DatatypeOrder.collect_dependencies_total_correct
#print axioms Rowl.DatatypeOrder.dependency_support
#print axioms Rowl.DatatypeOrder.check_acyclic_total_correct
#print axioms Rowl.DatatypeOrder.check_acyclic_accepted_iff
#print axioms Rowl.DatatypePositions.defined_datatype_total_correct
#print axioms Rowl.DatatypePositions.literal_allowed_total_correct
#print axioms Rowl.DatatypePositions.range_allowed_total_correct
#print axioms Rowl.DatatypePositions.class_allowed_total_correct
#print axioms Rowl.DatatypePositions.annotation_allowed_total_correct
#print axioms Rowl.DatatypePositions.body_allowed_total_correct
#print axioms Rowl.DatatypePositions.axiom_allowed_total_correct
#print axioms Rowl.DatatypePositions.check_positions_total_correct
#print axioms Rowl.DatatypePositions.check_positions_valid_iff
#print axioms Rowl.DatatypePositions.check_ontology_positions_total_correct
#print axioms Rowl.DatatypePositions.check_ontology_positions_valid_iff
#print axioms Rowl.DatatypeRestrictions.check_definition_rules_total_correct
#print axioms Rowl.DatatypeRestrictions.check_definition_rules_accepted_iff
#print axioms Rowl.DatatypeRestrictions.check_structural_datatypes_total_correct
#print axioms Rowl.DatatypeRestrictions.check_structural_datatypes_accepted_iff
#print axioms Rowl.ClassEquality.same_natural_total_correct
#print axioms Rowl.ClassEquality.same_natural_value_total_correct
#print axioms Rowl.ClassEquality.is_thing_total_correct
#print axioms Rowl.ClassEquality.is_literal_total_correct
#print axioms Rowl.ClassEquality.same_optional_range_total_correct
#print axioms Rowl.ClassEquality.same_individual_set_total_correct
#print axioms Rowl.ClassEquality.same_class_total_correct
#print axioms Rowl.ClassEquality.same_class_set_total_correct
#print axioms Rowl.ClassEquality.same_optional_class_total_correct
#print axioms Rowl.ClassEquality.class_eq_refl
#print axioms Rowl.ClassEquality.class_eq_symm
#print axioms Rowl.ClassEquality.class_eq_trans
#print axioms Rowl.Keys.axiom_allowed_total_correct
#print axioms Rowl.Keys.check_keys_total_correct
#print axioms Rowl.Keys.check_keys_valid_iff
#print axioms Rowl.Arity.same_data_property_total_correct
#print axioms Rowl.Arity.has_two_ranges_total_correct
#print axioms Rowl.Arity.has_two_classes_total_correct
#print axioms Rowl.Arity.unique_classes_total_correct
#print axioms Rowl.Arity.has_two_properties_total_correct
#print axioms Rowl.Arity.unique_properties_total_correct
#print axioms Rowl.Arity.has_two_data_properties_total_correct
#print axioms Rowl.Arity.unique_data_properties_total_correct
#print axioms Rowl.Arity.has_two_individuals_total_correct
#print axioms Rowl.Arity.unique_individuals_total_correct
#print axioms Rowl.Arity.range_allowed_total_correct
#print axioms Rowl.Arity.class_allowed_total_correct
#print axioms Rowl.Arity.axiom_allowed_total_correct
#print axioms Rowl.Arity.check_arities_total_correct
#print axioms Rowl.Arity.check_arities_valid_iff
#print axioms Rowl.AxiomEquality.same_entity_total_correct
#print axioms Rowl.AxiomEquality.same_subject_total_correct
#print axioms Rowl.AxiomEquality.same_properties_set_total_correct
#print axioms Rowl.AxiomEquality.same_properties_association_total_correct
#print axioms Rowl.AxiomEquality.same_data_properties_set_total_correct
#print axioms Rowl.AxiomEquality.same_data_properties_association_total_correct
#print axioms Rowl.AxiomEquality.same_individuals_association_total_correct
#print axioms Rowl.AxiomEquality.same_chain_total_correct
#print axioms Rowl.AxiomEquality.same_sub_property_total_correct
#print axioms Rowl.AxiomEquality.same_body_total_correct
#print axioms Rowl.AxiomEquality.same_axiom_total_correct
#print axioms Rowl.AxiomEquality.body_eq_refl
#print axioms Rowl.AxiomEquality.body_eq_symm
#print axioms Rowl.AxiomEquality.body_eq_trans
#print axioms Rowl.AxiomEquality.axiom_eq_refl
#print axioms Rowl.AxiomEquality.axiom_eq_symm
#print axioms Rowl.AxiomEquality.axiom_eq_trans
#print axioms Rowl.AxiomEquality.object_assertion_compatibility
#print axioms Rowl.AxiomEquality.datatype_definition_compatibility
#print axioms Rowl.StructuralCongruence.range_denotation
#print axioms Rowl.StructuralCongruence.interpretation_defaults
#print axioms Rowl.StructuralCongruence.defaults_with_anonymous
#print axioms Rowl.StructuralCongruence.class_denotation
#print axioms Rowl.StructuralCongruence.arity_implies_distinct_members
#print axioms Rowl.StructuralCongruence.subproperty_denotation
#print axioms Rowl.StructuralCongruence.body_satisfaction
#print axioms Rowl.StructuralCongruence.axiom_satisfaction
#print axioms Rowl.StructuralCongruence.compared_axioms_satisfaction
#print axioms Rowl.StructuralCongruence.closure_satisfaction
#print axioms Rowl.StructuralCongruence.closure_models
#print axioms Rowl.StructuralCongruence.closure_model
#print axioms Rowl.StructuralCongruence.closure_consistency
#print axioms Rowl.StructuralCongruence.source_entailment
#print axioms Rowl.StructuralCongruence.target_entailment
#print axioms Rowl.StructuralCongruence.disjoint_duplicates_require_validation
#print axioms Rowl.StructuralCongruence.object_defaults_require_interpretation
#print axioms Rowl.StructuralCongruence.data_defaults_require_interpretation
#print axioms Rowl.AxiomSet.build_total_correct
#print axioms Rowl.AxiomSet.originals_total_correct
#print axioms Rowl.AxiomSet.representatives_total_correct
#print axioms Rowl.AxiomSet.representative_indices_total_correct
#print axioms Rowl.AxiomSet.occurrence_total_correct
#print axioms Rowl.AxiomSet.representative_of_total_correct
#print axioms Rowl.AxiomSet.build_accepts_iff
#print axioms Rowl.AxiomSet.representatives_are_roots
#print axioms Rowl.AxiomSet.representative_indices_unique
#print axioms Rowl.AxiomSet.representative_order
#print axioms Rowl.AxiomSet.representatives_structurally_unique
#print axioms Rowl.AxiomSet.mapping_is_minimal_and_present
#print axioms Rowl.AxiomSet.representative_map_idempotent
#print axioms Rowl.AxiomSet.representative_closure_original
#print axioms Rowl.AxiomSet.representative_closure_valid
#print axioms Rowl.AxiomSet.representative_closure_equivalent
#print axioms Rowl.AxiomSet.representative_models
#print axioms Rowl.AxiomSet.representative_consistency
#print axioms Rowl.AxiomSet.representative_entailment
#print axioms Rowl.AxiomSet.successful_build_correct
#print axioms Rowl.Names.prefix_grammar_total_correct
#print axioms Rowl.Names.local_grammar_total_correct
#print axioms Rowl.Names.abbreviated_grammar_total_correct
#print axioms Rowl.Names.node_grammar_total_correct
#print axioms Rowl.Names.validate_prefix_total_correct
#print axioms Rowl.Names.validate_local_total_correct
#print axioms Rowl.Names.validate_abbreviated_total_correct
#print axioms Rowl.Names.validate_node_total_correct
#print axioms Rowl.Names.validate_prefix_accepted_iff
#print axioms Rowl.Names.validate_local_accepted_iff
#print axioms Rowl.Names.validate_abbreviated_accepted_iff
#print axioms Rowl.Names.validate_node_accepted_iff
#print axioms Rowl.Prefixes.standard_total_correct
#print axioms Rowl.Prefixes.namespace_total_correct
#print axioms Rowl.Prefixes.lookup_total_correct
#print axioms Rowl.Prefixes.check_total_correct
#print axioms Rowl.Prefixes.declarations_total_correct
#print axioms Rowl.Prefixes.check_accepts_iff
#print axioms Rowl.Prefixes.successful_check_correct
#print axioms Rowl.Prefixes.expand_parts_total_correct
#print axioms Rowl.Prefixes.expand_parts_accepts_iff
#print axioms Rowl.Prefixes.copy_total_correct
#print axioms Rowl.Prefixes.join_total_correct
#print axioms Rowl.Prefixes.join_result_iff
#print axioms Rowl.Longest.longest_prefix_total_correct
#print axioms Rowl.Longest.longest_prefix_matched_iff
#print axioms Rowl.Longest.longest_prefix_endpoint_bounds
#print axioms Rowl.Functional.keyword_words_injective
#print axioms Rowl.Functional.keyword_clone_total_correct
#print axioms Rowl.Functional.terminal_clone_total_correct
#print axioms Rowl.Functional.keyword_grammar_total_correct
#print axioms Rowl.Functional.grammar_total_correct
#print axioms Rowl.Functional.grammar_nonempty
#print axioms Rowl.Functional.recognize_total_correct
#print axioms Rowl.Functional.recognize_accepted_iff
#print axioms Rowl.Functional.longest_total_correct
#print axioms Rowl.Functional.longest_matched_iff
#print axioms Rowl.Functional.longest_advances
#print axioms Rowl.FunctionalSelection.inventory_complete
#print axioms Rowl.FunctionalSelection.next_terminal_total_correct
#print axioms Rowl.FunctionalSelection.next_terminal_selects_iff
#print axioms Rowl.FunctionalSelection.next_terminal_advances
#print axioms Rowl.FunctionalSelection.selected_token_unique
#print axioms Rowl.FunctionalSelection.next_terminal_token_iff
#print axioms Rowl.FunctionalPayload.escape_total_correct
#print axioms Rowl.FunctionalPayload.quoted_item_total_correct
#print axioms Rowl.FunctionalPayload.quoted_item_progress
#print axioms Rowl.FunctionalPayload.quoted_item_accepted_iff
#print axioms Rowl.FunctionalPayload.read_quoted_total_correct
#print axioms Rowl.FunctionalPayload.read_quoted_accepted_iff
#print axioms Rowl.FunctionalPayload.quoted_token_progress
#print axioms Rowl.FunctionalPayload.quoted_token_source
#print axioms Rowl.FunctionalPayload.quoted_token_source_iff
#print axioms Rowl.FunctionalPayload.read_quoted_source_complete
#print axioms Rowl.FunctionalPayload.read_quoted_error_iff
#print axioms Rowl.FunctionalLexer.delimiter_total_correct
#print axioms Rowl.FunctionalLexer.special_total_correct
#print axioms Rowl.FunctionalLexer.last_codepoint_total_correct
#print axioms Rowl.FunctionalLexer.separator_total_correct
#print axioms Rowl.FunctionalLexer.gap_allowed_bounds
#print axioms Rowl.FunctionalLexer.separator_next_iff
#print axioms Rowl.FunctionalLexer.separator_missing_iff
#print axioms Rowl.FunctionalLexer.lex_total_correct
#print axioms Rowl.FunctionalLexer.lex_tokens_iff
#print axioms Rowl.FunctionalLexer.lex_excludes_invalid_span
#print axioms Rowl.FunctionalLexer.lex_tokens_properties
#print axioms Rowl.FunctionalDisjointness.terminal_language_unique
#print axioms Rowl.FunctionalDisjointness.candidate_kind_unique
#print axioms Rowl.FunctionalDisjointness.greatest_correct_iff
#print axioms Rowl.FunctionalDisjointness.greatest_token_unique
#print axioms Rowl.FunctionalDisjointness.next_terminal_greatest_iff
#print axioms Rowl.Decimal.small_value_total_correct
#print axioms Rowl.Decimal.times_ten_total_correct
#print axioms Rowl.Decimal.read_span_total_correct
#print axioms Rowl.Decimal.read_total_correct
#print axioms Rowl.Decimal.read_span_accepted_iff
#print axioms Rowl.Decimal.read_accepted_iff
#print axioms Rowl.Decimal.read_span_error_is_first_digit
#print axioms Rowl.Decimal.read_span_accepts_iff
#print axioms Rowl.FunctionalIntegers.ascii_span_source
#print axioms Rowl.FunctionalIntegers.integer_language_iff
#print axioms Rowl.FunctionalIntegers.integer_candidate_iff
#print axioms Rowl.FunctionalIntegers.read_integer_iff
#print axioms Rowl.FunctionalIntegers.selected_integer_value
#print axioms Rowl.FunctionalIntegers.lex_integer_values
#print axioms Rowl.SourceSpans.source_unit
#print axioms Rowl.SourceSpans.utf8_source_iff
#print axioms Rowl.SourceSpans.source_length
#print axioms Rowl.SourceSpans.source_split
#print axioms Rowl.FunctionalNames.payload_grammar
#print axioms Rowl.FunctionalNames.read_span_total_correct
#print axioms Rowl.FunctionalNames.read_span_accepted_iff
#print axioms Rowl.FunctionalNames.read_span_accepts_iff
#print axioms Rowl.FunctionalNames.read_value_grammar
#print axioms Rowl.FunctionalNames.read_span_error_iff
#print axioms Rowl.FunctionalNames.selected_name_value
#print axioms Rowl.FunctionalNames.lex_name_values
#print axioms Rowl.FunctionalIriParts.partition_values
#print axioms Rowl.FunctionalIriParts.split_abbreviated_total_correct
#print axioms Rowl.FunctionalIriParts.split_abbreviated_accepts_iff
#print axioms Rowl.FunctionalIriParts.split_source_values
#print axioms Rowl.FunctionalIriParts.parts_value_unique
#print axioms Rowl.FunctionalIriParts.split_abbreviated_error_iff
#print axioms Rowl.FunctionalIriParts.split_abbreviated_value_iff
#print axioms Rowl.FunctionalIris.resolve_span_total_correct
#print axioms Rowl.FunctionalIris.resolve_span_value_iff
#print axioms Rowl.FunctionalIris.resolve_span_accepts_iff
#print axioms Rowl.FunctionalIris.resolve_span_error_iff
#print axioms Rowl.FunctionalIris.resolved_iri_grammar
#print axioms Rowl.FunctionalIris.internal_parts_error_unreachable
#print axioms Rowl.FunctionalPrefixShape.expected_terminal_total_correct
#print axioms Rowl.FunctionalPrefixShape.take_expected_total_correct
#print axioms Rowl.FunctionalPrefixShape.read_shape_total_correct
#print axioms Rowl.FunctionalPrefixShape.read_shape_result_iff
#print axioms Rowl.FunctionalPrefixShape.body_shape_count
#print axioms Rowl.FunctionalPrefixDeclaration.read_declaration_total_correct
#print axioms Rowl.FunctionalPrefixDeclaration.read_declaration_result_iff
#print axioms Rowl.FunctionalPrefixDeclaration.body_source_values
#print axioms Rowl.FunctionalPrefixDeclaration.declaration_value_grammars
#print axioms Rowl.FunctionalPrefixDeclaration.declaration_token_progress
#print axioms Rowl.FunctionalPrefixes.scan_prefixes_total_correct
#print axioms Rowl.FunctionalPrefixes.scan_prefixes_result_iff
#print axioms Rowl.FunctionalPrefixes.read_prefix_header_total_correct
#print axioms Rowl.FunctionalPrefixes.read_prefix_header_accepted_iff
#print axioms Rowl.FunctionalPrefixes.read_prefix_header_syntax_error_iff
#print axioms Rowl.FunctionalPrefixes.read_prefix_header_source
#print axioms Rowl.FunctionalPrefixes.checked_source_prefix_table
#print axioms Rowl.FunctionalPrefixes.invalid_span_unreachable
#print axioms Rowl.FunctionalPrefixResolution.source_iri_correct
#print axioms Rowl.FunctionalPrefixResolution.source_iri_value_iff
#print axioms Rowl.FunctionalPrefixResolution.source_iri_error_iff
#print axioms Rowl.FunctionalHeaderIdentity.iri_kind_total_correct
#print axioms Rowl.FunctionalHeaderIdentity.read_optional_iri_total_correct
#print axioms Rowl.FunctionalHeaderIdentity.read_optional_iri_result_iff
#print axioms Rowl.FunctionalHeaderIdentity.read_identity_total_correct
#print axioms Rowl.FunctionalHeaderIdentity.read_identity_result_iff
#print axioms Rowl.FunctionalHeaderIdentity.header_iri_grammar
#print axioms Rowl.FunctionalHeaderIdentity.optional_present_source
#print axioms Rowl.FunctionalHeaderIdentity.optional_absent_unchanged
#print axioms Rowl.FunctionalHeaderIdentity.identity_source_values
#print axioms Rowl.FunctionalHeaderShape.expected_terminal_total_correct
#print axioms Rowl.FunctionalHeaderShape.expected_iri_kind
#print axioms Rowl.FunctionalHeaderShape.take_expected_total_correct
#print axioms Rowl.FunctionalHeaderShape.read_import_shape_total_correct
#print axioms Rowl.FunctionalHeaderShape.read_import_shape_result_iff
#print axioms Rowl.FunctionalHeaderShape.import_shape_count
#print axioms Rowl.FunctionalHeaderImport.read_import_total_correct
#print axioms Rowl.FunctionalHeaderImport.read_import_result_iff
#print axioms Rowl.FunctionalHeaderImport.import_source_value
#print axioms Rowl.FunctionalHeaderImport.import_token_progress
#print axioms Rowl.FunctionalHeader.scan_imports_total_correct
#print axioms Rowl.FunctionalHeader.scan_imports_result_iff
#print axioms Rowl.FunctionalHeader.read_header_tail_total_correct
#print axioms Rowl.FunctionalHeader.read_header_tail_result_iff
#print axioms Rowl.FunctionalHeader.import_section_maximal
#print axioms Rowl.FunctionalHeader.header_source_values
#print axioms Rowl.FunctionalHeaderSource.source_header_result_iff
#print axioms Rowl.FunctionalHeaderSource.source_header_values
#print axioms Rowl.FunctionalLiteralShape.read_shape_total_correct
#print axioms Rowl.FunctionalLiteralShape.read_shape_result_iff
#print axioms Rowl.FunctionalLiteralShape.typed_shape_kind
#print axioms Rowl.FunctionalLiteralShape.shape_token_count
#print axioms Rowl.FunctionalLiteralValues.string_span_total_correct
#print axioms Rowl.FunctionalLiteralValues.string_span_value_iff
#print axioms Rowl.FunctionalLiteralValues.string_span_error_iff
#print axioms Rowl.FunctionalLiteralValues.plain_lexical_total_correct
#print axioms Rowl.FunctionalLiteralValues.plain_lexical_result_iff
#print axioms Rowl.FunctionalLiteralValues.plain_datatype_total_correct
#print axioms Rowl.FunctionalLiteralValues.plain_datatype_result_iff
#print axioms Rowl.FunctionalLiterals.read_literal_total_correct
#print axioms Rowl.FunctionalLiterals.read_literal_result_iff
#print axioms Rowl.FunctionalLiterals.finish_value_bounds
#print axioms Rowl.FunctionalLiterals.read_literal_source_values
#print axioms Rowl.FunctionalLiterals.finish_plain_expansion
#print axioms Rowl.FunctionalLiterals.finish_language_expansion
#print axioms Rowl.FunctionalLiterals.finish_typed_spelling
#print axioms Rowl.FunctionalLiterals.literal_token_progress
#print axioms Rowl.FunctionalLiteralSource.source_prefix_literal_result_iff
#print axioms Rowl.FunctionalLiteralSource.source_prefix_literal_derivation
#print axioms Rowl.FunctionalAnnotationParts.value_kind_total_correct
#print axioms Rowl.FunctionalAnnotationParts.expected_terminal_total_correct
#print axioms Rowl.FunctionalAnnotationParts.take_expected_total_correct
#print axioms Rowl.FunctionalAnnotationParts.take_expected_result_iff
#print axioms Rowl.FunctionalAnnotationParts.take_progress
#print axioms Rowl.FunctionalAnnotationParts.read_property_total_correct
#print axioms Rowl.FunctionalAnnotationParts.read_property_result_iff
#print axioms Rowl.FunctionalAnnotationParts.property_progress
#print axioms Rowl.FunctionalAnnotationParts.property_source_value
#print axioms Rowl.FunctionalAnnotationParts.read_value_total_correct
#print axioms Rowl.FunctionalAnnotationParts.read_value_result_iff
#print axioms Rowl.FunctionalAnnotationParts.literal_run_progress
#print axioms Rowl.FunctionalAnnotationParts.value_progress
#print axioms Rowl.FunctionalAnnotationParts.finish_annotation_total_correct
#print axioms Rowl.FunctionalAnnotationParts.finish_annotation_result_iff
#print axioms Rowl.FunctionalAnnotationParts.finish_progress
#print axioms Rowl.FunctionalAnnotations.scan_remaining_le
#print axioms Rowl.FunctionalAnnotations.scan_annotations_total_correct
#print axioms Rowl.FunctionalAnnotations.scan_annotations_result_iff
#print axioms Rowl.FunctionalAnnotations.read_annotations_total_correct
#print axioms Rowl.FunctionalAnnotations.read_annotations_result_iff
#print axioms Rowl.FunctionalAnnotations.read_annotations_accepted_iff
#print axioms Rowl.FunctionalAnnotations.section_maximal
#print axioms Rowl.FunctionalAnnotations.section_records
#print axioms Rowl.FunctionalAnnotations.section_token_count
#print axioms Rowl.FunctionalAnnotationSource.source_prefix_annotations_result_iff
#print axioms Rowl.FunctionalAnnotationSource.source_ontology_annotations
#print axioms Rowl.Owl.IsVocabulary
#print axioms Rowl.Owl.IsInterpretation
#print axioms Rowl.Owl.dataDenote
#print axioms Rowl.Owl.classDenote
#print axioms Rowl.Owl.satisfies
#print axioms Rowl.Owl.modelsClosure
#print axioms Rowl.Owl.Model
#print axioms Rowl.Owl.Consistent
#print axioms Rowl.Owl.Entails
#print axioms Rowl.Owl.ClassSatisfiable
#print axioms Rowl.Owl.Subsumed
#print axioms Rowl.Owl.InstanceOf
#print axioms Rowl.Owl.queryHolds
#print axioms Rowl.Owl.Answers
#print axioms Rowl.Imports.Correct
#print axioms Rowl.Imports.Reachable
#print axioms Rowl.Prepare.preparedSatisfies
#print axioms Rowl.Typing.WellTyped
#print axioms Rowl.Typing.Correct
#print axioms Rowl.Unicode.XmlChar
#print axioms Rowl.Unicode.Prefix
#print axioms Rowl.Unicode.StepCorrect
#print axioms Rowl.Unicode.TextFrom
#print axioms Rowl.Unicode.Rejected
#print axioms Rowl.Unicode.ScanCorrect
#print axioms Rowl.Snapshot.TextReady
#print axioms Rowl.Snapshot.SourceFailure
#print axioms Rowl.Snapshot.SourceCorrect
#print axioms Rowl.Snapshot.Correct
#print axioms Rowl.Batch.Corresponds
#print axioms Rowl.Collection.rows
#print axioms Rowl.Collection.entityUses
#print axioms Rowl.Collection.rangeUses
#print axioms Rowl.Collection.classUses
#print axioms Rowl.Collection.annotationUses
#print axioms Rowl.Collection.axiomUses
#print axioms Rowl.Collection.annotatedUses
#print axioms Rowl.Collection.declarationUses
#print axioms Rowl.Collection.Correct
#print axioms Rowl.Symbols.byteKeys
#print axioms Rowl.Symbols.WellFormed
#print axioms Rowl.Symbols.firstIndex
#print axioms Rowl.Symbols.InternCorrect
#print axioms Rowl.Builtins.entities
#print axioms Rowl.Builtins.role
#print axioms Rowl.Indexing.Encoded
#print axioms Rowl.Indexing.Extends
#print axioms Rowl.Indexing.AtCapacity
#print axioms Rowl.Indexing.EntitiesCorrect
#print axioms Rowl.Indexing.OntologyCorrect
#print axioms Rowl.Indexing.implicitRows
#print axioms Rowl.Indexing.TypingCorrect
#print axioms Rowl.Indexing.RowsWellTyped
#print axioms Rowl.Indexing.implicitSource
#print axioms Rowl.Indexing.ontologyUses
#print axioms Rowl.Indexing.ontologyDeclarations
#print axioms Rowl.Indexing.RawWellTyped
#print axioms Rowl.Collection.AxiomClosureCorrect
#print axioms Rowl.Rdf.graphRows
#print axioms Rowl.Rdf.graphNames
#print axioms Rowl.Rdf.NamesUnique
#print axioms Rowl.Rdf.GraphContains
#print axioms Rowl.Rdf.namedLookup
#print axioms Rowl.Rdf.requestedGraph
#print axioms Rowl.Rdf.RepeatedName
#print axioms Rowl.Rdf.SelectionCorrect
#print axioms Rowl.Vocabulary.reservedPrefixes
#print axioms Rowl.Vocabulary.Reserved
#print axioms Rowl.Vocabulary.EntityAllowed
#print axioms Rowl.Vocabulary.HeaderAllowed
#print axioms Rowl.Vocabulary.ontologyUses
#print axioms Rowl.Vocabulary.VocabularyOK
#print axioms Rowl.Vocabulary.FirstForbidden
#print axioms Rowl.Vocabulary.Correct
#print axioms Rowl.Regular.Denotes
#print axioms Rowl.Regular.Utf8From
#print axioms Rowl.Regular.Utf8Failure
#print axioms Rowl.Regular.MatchCorrect
#print axioms Rowl.Iri.Range
#print axioms Rowl.Iri.AtMost
#print axioms Rowl.Iri.IriLanguage
#print axioms Rowl.Iri.ReferenceLanguage
#print axioms Rowl.Iri.ValidationCorrect
#print axioms Rowl.Anonymous.Named
#print axioms Rowl.Anonymous.ClassAllowed
#print axioms Rowl.Anonymous.AxiomAllowed
#print axioms Rowl.Anonymous.PositionsOK
#print axioms Rowl.Anonymous.FirstForbidden
#print axioms Rowl.Encoding.Scalar
#print axioms Rowl.Encoding.Bytes
#print axioms Rowl.Encoding.EncodeCorrect
#print axioms Rowl.LangTag.WellFormedLanguage
#print axioms Rowl.LangTag.NormalLanguage
#print axioms Rowl.NTriples.UnitAt
#print axioms Rowl.NTriples.MalformedAt
#print axioms Rowl.NTriples.MalformedError
#print axioms Rowl.NTriples.AtCorrect
#print axioms Rowl.NTriples.RequiredError
#print axioms Rowl.NTriples.RequiredCorrect
#print axioms Rowl.NTriples.ExpectCorrect
#print axioms Rowl.NTriples.Horizontal
#print axioms Rowl.NTriples.EndLine
#print axioms Rowl.NTriples.CommentRuns
#print axioms Rowl.NTriples.CommentFails
#print axioms Rowl.NTriples.CommentCorrect
#print axioms Rowl.NTriples.Spacing
#print axioms Rowl.NTriples.TriviaRuns
#print axioms Rowl.NTriples.TriviaFails
#print axioms Rowl.NTriples.TriviaCorrect
#print axioms Rowl.NTriples.BufferAppend
#print axioms Rowl.NTriples.HexValue
#print axioms Rowl.NTriples.IriCharacter
#print axioms Rowl.NTriples.PnBase
#print axioms Rowl.NTriples.PnU
#print axioms Rowl.NTriples.AsciiDigit
#print axioms Rowl.NTriples.AsciiAlpha
#print axioms Rowl.NTriples.Pn
#print axioms Rowl.NTriples.BlankTail
#print axioms Rowl.NTriples.BlankTailFailure
#print axioms Rowl.NTriples.BlankTailCorrect
#print axioms Rowl.NTriples.CopyCorrect
#print axioms Rowl.NTriples.BlankToken
#print axioms Rowl.NTriples.BlankError
#print axioms Rowl.NTriples.BlankCorrect
#print axioms Rowl.NTriples.HexDigits
#print axioms Rowl.NTriples.HexError
#print axioms Rowl.NTriples.DigitsCorrect
#print axioms Rowl.NTriples.EcharValue
#print axioms Rowl.NTriples.EscapeValue
#print axioms Rowl.NTriples.EscapeError
#print axioms Rowl.NTriples.EscapeCorrect
#print axioms Rowl.NTriples.RawAllowed
#print axioms Rowl.NTriples.QuotedItem
#print axioms Rowl.NTriples.ItemError
#print axioms Rowl.NTriples.ItemCorrect
#print axioms Rowl.NTriples.Opening
#print axioms Rowl.NTriples.Closing
#print axioms Rowl.NTriples.OpeningErrorKind
#print axioms Rowl.NTriples.QuotedBody
#print axioms Rowl.NTriples.BodyError
#print axioms Rowl.NTriples.BodyCorrect
#print axioms Rowl.NTriples.QuotedToken
#print axioms Rowl.NTriples.QuotedError
#print axioms Rowl.NTriples.QuotedCorrect
#print axioms Rowl.NTriples.AbsoluteIri
#print axioms Rowl.NTriples.IriError
#print axioms Rowl.NTriples.IriCorrect
#print axioms Rowl.NTriples.SubjectToken
#print axioms Rowl.NTriples.SubjectError
#print axioms Rowl.NTriples.SubjectCorrect
#print axioms Rowl.TopData.TopBytes
#print axioms Rowl.TopData.RowsAllowed
#print axioms Rowl.TopData.AxiomAllowed
#print axioms Rowl.TopData.ClosureOK
#print axioms Rowl.TopData.FirstForbidden
#print axioms Rowl.NTriples.TagCharacter
#print axioms Rowl.NTriples.TagWord
#print axioms Rowl.NTriples.TagWordError
#print axioms Rowl.NTriples.TagWordCorrect
#print axioms Rowl.NTriples.TagSuffix
#print axioms Rowl.NTriples.TagSuffixError
#print axioms Rowl.NTriples.TagSuffixCorrect
#print axioms Rowl.NTriples.LanguageTag
#print axioms Rowl.NTriples.TagToken
#print axioms Rowl.NTriples.TagError
#print axioms Rowl.NTriples.TagCorrect
#print axioms Rowl.NTriples.XsdStringBytes
#print axioms Rowl.NTriples.LangStringBytes
#print axioms Rowl.NTriples.NoKindSuffix
#print axioms Rowl.NTriples.KindToken
#print axioms Rowl.NTriples.KindError
#print axioms Rowl.NTriples.KindCorrect
#print axioms Rowl.NTriples.LiteralToken
#print axioms Rowl.NTriples.LiteralError
#print axioms Rowl.NTriples.LiteralCorrect
#print axioms Rowl.NTriples.ObjectToken
#print axioms Rowl.NTriples.ObjectError
#print axioms Rowl.NTriples.ObjectCorrect
#print axioms Rowl.NTriples.LineBoundary
#print axioms Rowl.NTriples.LineError
#print axioms Rowl.NTriples.LineCorrect
#print axioms Rowl.NTriples.TriplePredicate
#print axioms Rowl.NTriples.TripleObject
#print axioms Rowl.NTriples.TripleTerminated
#print axioms Rowl.NTriples.TripleToken
#print axioms Rowl.NTriples.TripleError
#print axioms Rowl.NTriples.TripleCorrect
#print axioms Rowl.NTriples.DocumentTail
#print axioms Rowl.NTriples.DocumentTailError
#print axioms Rowl.NTriples.DocumentTailCorrect
#print axioms Rowl.NTriples.Document
#print axioms Rowl.NTriples.DocumentError
#print axioms Rowl.NTriples.DocumentCorrect
#print axioms Rowl.NTriples.ReadCorrect
#print axioms Rowl.Roles.key
#print axioms Rowl.Roles.inverse
#print axioms Rowl.Roles.expressionKey
#print axioms Rowl.Roles.roleKeys
#print axioms Rowl.Roles.edgeKeys
#print axioms Rowl.Roles.chainKeys
#print axioms Rowl.Roles.Nodes
#print axioms Rowl.Roles.TopBytes
#print axioms Rowl.Roles.BottomBytes
#print axioms Rowl.Roles.BuiltinComposite
#print axioms Rowl.Roles.BuiltinSeeds
#print axioms Rowl.Roles.Directed
#print axioms Rowl.Roles.Equivalent
#print axioms Rowl.Roles.Pairs
#print axioms Rowl.Roles.PropertyKeys
#print axioms Rowl.Roles.ClassRequired
#print axioms Rowl.Roles.AxiomRequired
#print axioms Rowl.Roles.AxiomEdges
#print axioms Rowl.Roles.AxiomSeeds
#print axioms Rowl.Roles.AxiomChains
#print axioms Rowl.Roles.Correct
#print axioms Rowl.Roles.ClosureCorrect
#print axioms Rowl.Roles.Hierarchy
#print axioms Rowl.Roles.Reachable
#print axioms Rowl.Roles.Composite
#print axioms Rowl.Roles.Simple
#print axioms Rowl.Roles.SimpleRestriction
#print axioms Rowl.Roles.ChainOrdered
#print axioms Rowl.Roles.AllNodes
#print axioms Rowl.Roles.Regular
#print axioms Rowl.RoleClosure.Reach
#print axioms Rowl.RoleClosure.Correct
#print axioms Rowl.RoleClosure.SimplicityCorrect
#print axioms Rowl.RoleOrder.Derived
#print axioms Rowl.RoleOrder.Universe
#print axioms Rowl.RoleOrder.Correct
#print axioms Rowl.RoleOrder.TrimLast
#print axioms Rowl.RoleOrder.Selected
#print axioms Rowl.RoleOrder.Top
#print axioms Rowl.RoleOrder.ChainSeeds
#print axioms Rowl.RoleOrder.Seeds
#print axioms Rowl.RoleOrder.Witness
#print axioms Rowl.RoleOrder.RegularityCorrect
#print axioms Rowl.Anonymous.NoAnonymousAnnotation
#print axioms Rowl.Anonymous.AnnotationPositionsAllowed
#print axioms Rowl.Anonymous.AnnotatedAllowed
#print axioms Rowl.AnonymousGraph.key
#print axioms Rowl.AnonymousGraph.edgeKeys
#print axioms Rowl.AnonymousGraph.axiomEdges
#print axioms Rowl.AnonymousGraph.closureEdges
#print axioms Rowl.AnonymousGraph.HasPair
#print axioms Rowl.AnonymousGraph.graph
#print axioms Rowl.AnonymousGraph.Forest
#print axioms Rowl.AnonymousGraph.Correct
#print axioms Rowl.Owl.Utf8Lexical
#print axioms Rowl.AssertionEquality.AnnotationEq
#print axioms Rowl.AssertionEquality.AnnotationSetEq
#print axioms Rowl.AssertionEquality.AssertionEq
#print axioms Rowl.AnonymousMultiplicity.SamePair
#print axioms Rowl.AnonymousMultiplicity.Conflict
#print axioms Rowl.AnonymousMultiplicity.Restriction
#print axioms Rowl.AnonymousMultiplicity.Correct
#print axioms Rowl.AnonymousBoundary.First
#print axioms Rowl.AnonymousBoundary.Second
#print axioms Rowl.AnonymousBoundary.Candidates
#print axioms Rowl.AnonymousBoundary.TouchesNamed
#print axioms Rowl.AnonymousBoundary.AtMostOne
#print axioms Rowl.AnonymousBoundary.Restriction
#print axioms Rowl.AnonymousBoundary.Correct
#print axioms Rowl.AnonymousRestrictions.Restriction
#print axioms Rowl.AnonymousRestrictions.Correct
#print axioms Rowl.RangeEquality.Members
#print axioms Rowl.RangeEquality.SetEq
#print axioms Rowl.RangeEquality.RangeEq
#print axioms Rowl.RangeEquality.RangeSetEq
#print axioms Rowl.RangeEquality.DefinitionEq
#print axioms Rowl.DatatypeDefinitions.Predefined
#print axioms Rowl.DatatypeDefinitions.Defines
#print axioms Rowl.DatatypeDefinitions.SingleDefinition
#print axioms Rowl.DatatypeDefinitions.Available
#print axioms Rowl.DatatypeDefinitions.RowRestriction
#print axioms Rowl.DatatypeDefinitions.Restriction
#print axioms Rowl.DatatypeDefinitions.AtCorrect
#print axioms Rowl.DatatypeDefinitions.Correct
#print axioms Rowl.DatatypeOrder.edgeKeys
#print axioms Rowl.DatatypeOrder.useEdges
#print axioms Rowl.DatatypeOrder.axiomEdges
#print axioms Rowl.DatatypeOrder.closureEdges
#print axioms Rowl.DatatypeOrder.Reach
#print axioms Rowl.DatatypeOrder.Path
#print axioms Rowl.DatatypeOrder.Acyclic
#print axioms Rowl.DatatypeOrder.Order
#print axioms Rowl.DatatypeOrder.DatatypeNodes
#print axioms Rowl.DatatypeOrder.OrderOn
#print axioms Rowl.DatatypeOrder.Restriction
#print axioms Rowl.DatatypeOrder.Correct
#print axioms Rowl.DatatypePositions.Defined
#print axioms Rowl.DatatypePositions.LiteralAllowed
#print axioms Rowl.DatatypePositions.FacetAllowed
#print axioms Rowl.DatatypePositions.ValueAllowed
#print axioms Rowl.DatatypePositions.RangeAllowed
#print axioms Rowl.DatatypePositions.ClassAllowed
#print axioms Rowl.DatatypePositions.AnnotationAllowed
#print axioms Rowl.DatatypePositions.BodyAllowed
#print axioms Rowl.DatatypePositions.AnnotatedAllowed
#print axioms Rowl.DatatypePositions.ClosureOK
#print axioms Rowl.DatatypePositions.FirstForbidden
#print axioms Rowl.DatatypePositions.FirstAnnotation
#print axioms Rowl.DatatypePositions.OntologyOK
#print axioms Rowl.DatatypePositions.Correct
#print axioms Rowl.DatatypeRestrictions.Restriction
#print axioms Rowl.DatatypeRestrictions.Correct
#print axioms Rowl.DatatypeRestrictions.StructuralRestriction
#print axioms Rowl.DatatypeRestrictions.StructuralCorrect
#print axioms Rowl.ClassEquality.Members
#print axioms Rowl.ClassEquality.ThingBytes
#print axioms Rowl.ClassEquality.LiteralBytes
#print axioms Rowl.ClassEquality.IsThing
#print axioms Rowl.ClassEquality.IsLiteral
#print axioms Rowl.ClassEquality.OptionalRangeEq
#print axioms Rowl.ClassEquality.ClassEq
#print axioms Rowl.ClassEquality.ClassSetEq
#print axioms Rowl.ClassEquality.OptionalClassEq
#print axioms Rowl.Keys.AxiomAllowed
#print axioms Rowl.Keys.ClosureOK
#print axioms Rowl.Keys.FirstForbidden
#print axioms Rowl.Arity.TwoDistinct
#print axioms Rowl.Arity.Unique
#print axioms Rowl.Arity.RangeAllowed
#print axioms Rowl.Arity.ClassAllowed
#print axioms Rowl.Arity.AxiomAllowed
#print axioms Rowl.Arity.ClosureOK
#print axioms Rowl.Arity.FirstForbidden
#print axioms Rowl.AxiomEquality.SubPropertyEq
#print axioms Rowl.AxiomEquality.BodyEq
#print axioms Rowl.AxiomEquality.AxiomEq
#print axioms Rowl.StructuralCongruence.Defaults
#print axioms Rowl.StructuralCongruence.MatchSet
#print axioms Rowl.StructuralCongruence.DistinctMembers
#print axioms Rowl.StructuralCongruence.ClosureEq
#print axioms Rowl.StructuralCongruence.ClassFiller
#print axioms Rowl.StructuralCongruence.RangeFiller
#print axioms Rowl.AxiomSet.Closure
#print axioms Rowl.AxiomSet.Valid
#print axioms Rowl.AxiomSet.FirstForbidden
#print axioms Rowl.AxiomSet.MatchAt
#print axioms Rowl.AxiomSet.FirstRepresentative
#print axioms Rowl.AxiomSet.Roots
#print axioms Rowl.AxiomSet.IndexInvariant
#print axioms Rowl.AxiomSet.WellFormed
#print axioms Rowl.AxiomSet.Correct
#print axioms Rowl.AxiomSet.RepresentativeClosure
#print axioms Rowl.Names.BaseCode
#print axioms Rowl.Names.Base
#print axioms Rowl.Names.CharsU
#print axioms Rowl.Names.Chars
#print axioms Rowl.Names.Ending
#print axioms Rowl.Names.PrefixWord
#print axioms Rowl.Names.Local
#print axioms Rowl.Names.Prefix
#print axioms Rowl.Names.Abbreviated
#print axioms Rowl.Names.Node
#print axioms Rowl.Prefixes.StandardName
#print axioms Rowl.Prefixes.Namespace
#print axioms Rowl.Prefixes.StandardFor
#print axioms Rowl.Prefixes.PrefixAccepted
#print axioms Rowl.Prefixes.LocalAccepted
#print axioms Rowl.Prefixes.IriAccepted
#print axioms Rowl.Prefixes.DeclarationValid
#print axioms Rowl.Prefixes.TableValid
#print axioms Rowl.Prefixes.WellFormed
#print axioms Rowl.Prefixes.Scan
#print axioms Rowl.Prefixes.Lookup
#print axioms Rowl.Prefixes.Joined
#print axioms Rowl.Prefixes.ExpansionCorrect
#print axioms Rowl.Longest.Utf8Span
#print axioms Rowl.Longest.Candidate
#print axioms Rowl.Longest.Maximal
#print axioms Rowl.Longest.Correct
#print axioms Rowl.Functional.Word
#print axioms Rowl.Functional.KeywordWord
#print axioms Rowl.Functional.IntegerLanguage
#print axioms Rowl.Functional.QuotedRaw
#print axioms Rowl.Functional.QuotedBody
#print axioms Rowl.Functional.QuotedLanguage
#print axioms Rowl.Functional.Space
#print axioms Rowl.Functional.WhitespaceLanguage
#print axioms Rowl.Functional.CommentRaw
#print axioms Rowl.Functional.CommentLanguage
#print axioms Rowl.Functional.TerminalLanguage
#print axioms Rowl.FunctionalSelection.AllTerminals
#print axioms Rowl.FunctionalSelection.Candidate
#print axioms Rowl.FunctionalSelection.FirstCandidate
#print axioms Rowl.FunctionalSelection.Correct
#print axioms Rowl.FunctionalPayload.EscapeMarker
#print axioms Rowl.FunctionalPayload.RawAllowed
#print axioms Rowl.FunctionalPayload.EscapeValue
#print axioms Rowl.FunctionalPayload.EscapeError
#print axioms Rowl.FunctionalPayload.EscapeCorrect
#print axioms Rowl.FunctionalPayload.QuotedItem
#print axioms Rowl.FunctionalPayload.ItemError
#print axioms Rowl.FunctionalPayload.ItemCorrect
#print axioms Rowl.FunctionalPayload.QuotedBody
#print axioms Rowl.FunctionalPayload.BodyError
#print axioms Rowl.FunctionalPayload.BodyCorrect
#print axioms Rowl.FunctionalPayload.QuotedToken
#print axioms Rowl.FunctionalPayload.QuotedError
#print axioms Rowl.FunctionalPayload.QuotedCorrect
#print axioms Rowl.FunctionalLexer.Delimiter
#print axioms Rowl.FunctionalLexer.Special
#print axioms Rowl.FunctionalLexer.LastCorrect
#print axioms Rowl.FunctionalLexer.Ending
#print axioms Rowl.FunctionalLexer.LeadingDelimiter
#print axioms Rowl.FunctionalLexer.Ready
#print axioms Rowl.FunctionalLexer.GapAllowed
#print axioms Rowl.FunctionalLexer.GapMissing
#print axioms Rowl.FunctionalLexer.GapCorrect
#print axioms Rowl.FunctionalLexer.WithToken
#print axioms Rowl.FunctionalLexer.Run
#print axioms Rowl.FunctionalLexer.Correct
#print axioms Rowl.FunctionalLexer.TokenCount
#print axioms Rowl.FunctionalLexer.Stream
#print axioms Rowl.FunctionalDisjointness.Greatest
#print axioms Rowl.Decimal.Digit
#print axioms Rowl.Decimal.Digits
#print axioms Rowl.Decimal.Numeric
#print axioms Rowl.Decimal.Slice
#print axioms Rowl.Decimal.BadDigit
#print axioms Rowl.Decimal.ScanCorrect
#print axioms Rowl.Decimal.ErrorCorrect
#print axioms Rowl.Decimal.Correct
#print axioms Rowl.FunctionalIntegers.WordValue
#print axioms Rowl.FunctionalIntegers.IntegerValues
#print axioms Rowl.SourceSpans.Bytes
#print axioms Rowl.FunctionalNames.TerminalOf
#print axioms Rowl.FunctionalNames.Leading
#print axioms Rowl.FunctionalNames.Trailing
#print axioms Rowl.FunctionalNames.Token
#print axioms Rowl.FunctionalNames.Payload
#print axioms Rowl.FunctionalNames.ValueLanguage
#print axioms Rowl.FunctionalNames.ErrorCorrect
#print axioms Rowl.FunctionalNames.Correct
#print axioms Rowl.FunctionalNames.NameValues
#print axioms Rowl.FunctionalIriParts.Partition
#print axioms Rowl.FunctionalIriParts.PartsValue
#print axioms Rowl.FunctionalIriParts.SplitError
#print axioms Rowl.FunctionalIriParts.SplitCorrect
#print axioms Rowl.FunctionalIris.Success
#print axioms Rowl.FunctionalIris.ErrorCorrect
#print axioms Rowl.FunctionalIris.Correct
#print axioms Rowl.FunctionalIris.Admissible
#print axioms Rowl.FunctionalPrefixShape.Expected
#print axioms Rowl.FunctionalPrefixShape.Taken
#print axioms Rowl.FunctionalPrefixShape.Mismatch
#print axioms Rowl.FunctionalPrefixShape.TakeCorrect
#print axioms Rowl.FunctionalPrefixShape.BodyShape
#print axioms Rowl.FunctionalPrefixShape.ShapeCorrect
#print axioms Rowl.FunctionalPrefixDeclaration.BodyRun
#print axioms Rowl.FunctionalPrefixes.Run
#print axioms Rowl.FunctionalPrefixes.Correct
#print axioms Rowl.FunctionalPrefixes.Section
#print axioms Rowl.FunctionalHeaderIdentity.Kind
#print axioms Rowl.FunctionalHeaderIdentity.IriValue
#print axioms Rowl.FunctionalHeaderIdentity.OptionalRun
#print axioms Rowl.FunctionalHeaderIdentity.IdentityRun
#print axioms Rowl.FunctionalHeaderIdentity.IdentityValues
#print axioms Rowl.FunctionalHeaderShape.Expected
#print axioms Rowl.FunctionalHeaderShape.Taken
#print axioms Rowl.FunctionalHeaderShape.Mismatch
#print axioms Rowl.FunctionalHeaderShape.TakeCorrect
#print axioms Rowl.FunctionalHeaderShape.BodyShape
#print axioms Rowl.FunctionalHeaderShape.ShapeCorrect
#print axioms Rowl.FunctionalHeaderImport.BodyRun
#print axioms Rowl.FunctionalHeader.ScanRun
#print axioms Rowl.FunctionalHeader.TailRun
#print axioms Rowl.FunctionalHeader.ImportSection
#print axioms Rowl.FunctionalLiteralShape.TailShape
#print axioms Rowl.FunctionalLiteralShape.BodyShape
#print axioms Rowl.FunctionalLiteralShape.ShapeError
#print axioms Rowl.FunctionalLiteralShape.ShapeCorrect
#print axioms Rowl.FunctionalLiteralShape.FormTokens
#print axioms Rowl.FunctionalLiteralValues.StringValue
#print axioms Rowl.FunctionalLiteralValues.SpanError
#print axioms Rowl.FunctionalLiteralValues.SpanCorrect
#print axioms Rowl.FunctionalLiteralValues.PlainDatatype
#print axioms Rowl.FunctionalLiteralValues.PlainLexical
#print axioms Rowl.FunctionalLiteralValues.DatatypeCorrect
#print axioms Rowl.FunctionalLiterals.WithSuffix
#print axioms Rowl.FunctionalLiterals.FinishRun
#print axioms Rowl.FunctionalLiterals.Run
#print axioms Rowl.FunctionalAnnotationParts.ValueKind
#print axioms Rowl.FunctionalAnnotationParts.Expected
#print axioms Rowl.FunctionalAnnotationParts.TakeRun
#print axioms Rowl.FunctionalAnnotationParts.PropertyRun
#print axioms Rowl.FunctionalAnnotationParts.ValueRun
#print axioms Rowl.FunctionalAnnotationParts.FinishRun
#print axioms Rowl.FunctionalAnnotations.ScanRun
#print axioms Rowl.FunctionalAnnotations.Section
