[workspace]
members = ["crates/rowl-kernel", "crates/rowl-frontend", "crates/rowl", "crates/rowl-cli"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
